name: Bot Boca Juniors

on:
 schedule:
    - cron: '0 12 * * *' # <--- ESTO significa: "Todos los días a las 12:00 UTC (09:00 AM de Argentina)"
  workflow_dispatch: # Te deja probarlo manualmente con un botón

jobs:
  correr-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar tu código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: Ejecutar Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
