name: Bot Boca Juniors

on:
  schedule:
    - cron: '0 12 * * *'  # 09:00 AM Argentina (mañana)
    - cron: '0 0 * * *'   # 21:00 PM Argentina (noche)
  workflow_dispatch: # Te deja probarlo manualmente con un botón

jobs:
  correr-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar tu código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: Ejecutar Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
